
topnav_title: Comdb2
# this appears on the top navigation bar next to the home button

site_title: Comdb2 Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

feedback_uuid: 15833401
# used as a contact email for the Feedback link in the top navigation bar

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: mydoc_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: mydoc_sidebar
# these are defaults used for the frontmatter for these file types

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build


#### IGNORE BELOW HERE ####

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 8080
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
